# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: movieshop-orders-api

provider:
  apiGateway:
    shouldStartNameWithService: true
  name: aws
  runtime: nodejs16.x
  stage: movieshop-ne-dev
  region: eu-central-1
  environment:
    CB_DYNAMO_DB_ORDERS: ${ssm:${self:custom.stage}-movieshop-orders}
    CB_STAGE: ${opt:stage, self:provider.stage}
    CB_SERVICE: ${self:service}
    CB_JWT_SECRET: ${ssm:${self:custom.stage}-jwt-secret}

custom:
    allowed-headers:
      - Content-Type
      - X-Amz-Date
      - Authorization
      - X-Api-Key
      - X-Amz-Security-Token
      - X-Amz-User-Agent
      - X-Cowabunga
    stage: ${opt:stage, self:provider.stage}
    region: ${opt:region, self:provider.region}

functions:

  create_space:
    role: ${ssm:${self:custom.stage}-orders-role}
    handler: orders/create.create
    events:
      - http:
          path: users/{id}/orders
          method: post
          cors: true

  get_space:
    role: ${ssm:${self:custom.stage}-orders-role}
    handler: orders/get.get
    events:
      - http:
          path: users/{id}/orders/{idSpace}
          method: get
          cors: true

  update_space:
    role: ${ssm:${self:custom.stage}-orders-role}
    handler: orders/update.update
    events:
      - http:
          path: users/{id}/orders/{idSpace}
          method: put
          cors: true

  delete_space:
    role: ${ssm:${self:custom.stage}-orders-role}
    handler: orders/delete.delete
    events:
      - http:
          path: users/{id}/orders/{idSpace}
          method: delete
          cors: true

  list_orders:
    role: ${ssm:${self:custom.stage}-orders-role}
    handler: orders/list.list
    events:
      - http:
          path: users/{id}/orders
          method: get
          cors: true