service: movieshop-pendentorders-api

provider:
  apiGateway:
    shouldStartNameWithService: true
  name: aws
  runtime: nodejs16.x
  stage: movieshop-nl-dev
  region: eu-central-1
  environment:
    CB_DYNAMO_DB_PENDENT_ORDERS: ${ssm:${self:custom.stage}-movieshop-pendentorders}
    CB_STAGE: ${opt:stage, self:provider.stage}
    CB_SERVICE: ${self:service}
    CB_JWT_SECRET: ${ssm:${self:custom.stage}-jwt-secret}

custom:
    allowed-headers:
      - Content-Type
      - X-Amz-Date
      - Authorization
      - X-Api-Key
      - X-Amz-Security-Token
      - X-Amz-User-Agent
      - X-Cowabunga
    stage: ${opt:stage, self:provider.stage}
    region: ${opt:region, self:provider.region}

functions:

  list_pendentorders:
    role: ${ssm:${self:custom.stage}-pendentorders-role}
    handler: pendentorders/list.list
    layers:
      - arn:aws:lambda:eu-central-1:637423312381:layer:movieshop-libutils:7
    events:
      - http:
          path: merchants/{id}/pendentorders
          method: get
          cors: true