# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: movieshop-lambda-probs
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs16.x
  stage: movieshop-nl-dev
  region: eu-central-1
  environment:
    MOVIESHOP_DYNAMO_DB_PROBS: ${ssm:${self:custom.stage}-movieshop-probs}
    MOVIESHOP_STAGE: ${opt:stage, self:provider.stage}
    MOVIESHOP_SERVICE: ${self:service}

custom:
    allowed-headers:
    stage: ${opt:stage, self:provider.stage}
    region: ${opt:region, self:provider.region}

functions:
  addprob:
    role: ${ssm:${self:custom.stage}-probs-role}
    handler: probs/create.create
  getprob:
    role: ${ssm:${self:custom.stage}-probs-role}
    handler: probs/get.get
    events:
      - http:
          path: probs/{id}
          method: get
          cors: true
  create_br_probs:
    role: ${ssm:${self:custom.stage}-probs-role}
    handler: probs/create-br-probs.create

  create_en_probs:
    role: ${ssm:${self:custom.stage}-probs-role}
    handler: probs/create-en-probs.create
