
service: movieshop-order-lambda-consumer

provider:
  name: aws
  runtime: nodejs16.x

# you can overwrite defaults here
  stage: movieshop-nl-dev
  region: eu-central-1

functions:
  stream_listener:
    handler: handler.listen
    role: ${ssm:${self:custom.stage}-orders-stream-consumer-role}
    events:
      - stream: ${ssm:${self:custom.stage}-orders-stream}
    environment:
      SNS_ORDER_NOTIFICATIONS_TOPIC: ${ssm:${self:custom.stage}-order-notifications-topic}
custom:
    stage: ${opt:stage, self:provider.stage}